### ISSUE TITLE
Unexpected Free Blk

### ISSUE THREAD

**Issue by timtadh** [timtadh/fs2#1]
**edit** 2015-06-12 : This seems to be a very rare error. I have only seen it this once. Not exactly sure what caused it, it looks like either an error in leafInsert returning the wrong value of a key or perhaps a dangling pointer. Not sure how that would have happened since the program using this was never deleting items from the tree. I will keep my eye out for it.

```
2015/06/10 14:31:59 unexpected free blk
goroutine 183064 [running]:
github.com/timtadh/fs2/errors.Errorf(0x614490, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/errors/error.go:16 +0x92
github.com/timtadh/fs2/bptree.func·144(0x7f03f021be60, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/varchar.go:558 +0x62
github.com/timtadh/fs2/bptree.func·149(0x7f03f021be60, 0x1a0, 0x1a0, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/varchar.go:605 +0x13d
github.com/timtadh/fs2/fmap.(*BlockFile).Do(0xc20d9214c0, 0xbb1d000, 0x1, 0xc20dc653f0, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/fmap/fmap.go:558 +0xbf
github.com/timtadh/fs2/bptree.(*Varchar).do(0xc20f280f60, 0xbb1de60, 0x64a340, 0x64a348, 0x64a338, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/varchar.go:611 +0xc1
github.com/timtadh/fs2/bptree.(*Varchar).doRun(0xc20f280f60, 0xbb1de60, 0x64a338, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/varchar.go:560 +0x66
github.com/timtadh/fs2/bptree.(*Varchar).Ref(0xc20f280f60, 0xbb1de60, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/varchar.go:507 +0x50
github.com/timtadh/fs2/bptree.(*internal).bigUpdateK(0x7f03e470f000, 0xc20f280f60, 0x0, 0x7f03e47fe020, 0x8, 0xfe0, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/internal.go:181 +0x147
github.com/timtadh/fs2/bptree.(*internal).updateK(0x7f03e470f000, 0xc20f280f60, 0x0, 0x7f03e47fe020, 0x8, 0xfe0, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/internal.go:168 +0x115
github.com/timtadh/fs2/bptree.func·072(0x7f03e47fe020, 0x8, 0xfe0, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/insert.go:143 +0x77
github.com/timtadh/fs2/bptree.func·023(0x7f03e47fe000, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/first.go:20 +0x124
github.com/timtadh/fs2/bptree.func·021(0x7f03e47fe000, 0x1000, 0x1000, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/do.go:103 +0xdd
github.com/timtadh/fs2/fmap.(*BlockFile).Do(0xc20d9214c0, 0x100000, 0x1, 0xc20dc65750, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/fmap/fmap.go:558 +0xbf
github.com/timtadh/fs2/bptree.(*BpTree).do(0xc20ff232e0, 0x100000, 0xc20dc657b0, 0xc20dc657a0, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/do.go:107 +0x79
github.com/timtadh/fs2/bptree.(*BpTree).firstKey(0xc20ff232e0, 0x100000, 0xc20dc65840, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/first.go:22 +0x84
github.com/timtadh/fs2/bptree.func·074(0x7f03e470f000, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/insert.go:144 +0x12d
github.com/timtadh/fs2/bptree.func·021(0x7f03e470f000, 0x1000, 0x1000, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/do.go:101 +0x8f
github.com/timtadh/fs2/fmap.(*BlockFile).Do(0xc20d9214c0, 0x11000, 0x1, 0xc20dc65988, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/fmap/fmap.go:558 +0xbf
github.com/timtadh/fs2/bptree.(*BpTree).do(0xc20ff232e0, 0x11000, 0xc20dc65aa8, 0x64a318, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/do.go:107 +0x79
github.com/timtadh/fs2/bptree.(*BpTree).doInternal(0xc20ff232e0, 0x11000, 0xc20dc65aa8, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/do.go:43 +0x5a
github.com/timtadh/fs2/bptree.(*BpTree).internalInsert(0xc20ff232e0, 0x11000, 0xc20c11c820, 0x18c, 0x18c, 0xc209de2f40, 0x1, 0x1, 0x49fc3a, 0xc20ff232e0, ...)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/insert.go:160 +0x273
github.com/timtadh/fs2/bptree.(*BpTree).insert(0xc20ff232e0, 0x11000, 0xc20c11c820, 0x18c, 0x18c, 0xc209de2f40, 0x1, 0x1, 0xc20dc65be0, 0x0, ...)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/insert.go:100 +0x138
github.com/timtadh/fs2/bptree.(*BpTree).internalInsert(0xc20ff232e0, 0x7da2000, 0xc20c11c820, 0x18c, 0x18c, 0xc209de2f40, 0x1, 0x1, 0x49fec9, 0xc20d9214c0, ...)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/insert.go:134 +0x17a
github.com/timtadh/fs2/bptree.(*BpTree).insert(0xc20ff232e0, 0x7da2000, 0xc20c11c820, 0x18c, 0x18c, 0xc209de2f40, 0x1, 0x1, 0x0, 0x0, ...)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/insert.go:100 +0x138
github.com/timtadh/fs2/bptree.(*BpTree).Add(0xc20ff232e0, 0xc20c11c820, 0x18c, 0x18c, 0xc209de2f40, 0x1, 0x1, 0x0, 0x0)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fs2/bptree/insert.go:54 +0x2fd
github.com/timtadh/fsm/mine.addToLabels(0xc20ff232e0, 0xc20c11c820, 0x18c, 0x18c)
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fsm/mine/maximal.go:65 +0x1c9
github.com/timtadh/fsm/mine.func·024()
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fsm/mine/maximal.go:46 +0x3e5
created by github.com/timtadh/fsm/mine.MaximalSubGraphs
        /home/hendersont/stuff/research/fsm/src/github.com/timtadh/fsm/mine/maximal.go:55 +0x345
```

**Comment by timtadh** [comment]
This was almost certainly caused by errors in remove/insert where-by a block was allocated twice by the Varchar subsystem and freed twice. I am going to close this issue as it is not specific enough.
