### ISSUE TITLE
Internal double put

### ISSUE THREAD

**Issue by timtadh** [timtadh/fs2#3]
```
2015/11/29 22:19:15 <internal (debug) (vchar <nil>) meta: <{1 4 3 340}>, keys: <[[0 0 0 28] [0 0 11 92] [0 0 16 0]]>, ptrs: <[1024000 819200 819200]>>
2015/11/29 22:19:15 key [0 0 11 92] v was nil
2015/11/29 22:19:15 replacing [0 0 16 0]
2015/11/29 22:19:15 <internal (debug) (vchar <nil>) meta: <{1 4 3 340}>, keys: <[[0 0 0 28] [0 0 11 92] [0 0 16 0]]>, ptrs: <[1024000 819200 819200]>>
2015/11/29 22:19:15 was removing: [0 0 16 0]
2015/11/29 22:19:15 n: 831488, parent: 0, sibling: 0, okid 823296, kid: 819200
2015/11/29 22:19:15 internal already had key [0 0 11 92], at 1, was going to put it at 2, replacing [0 0 16 0]
goroutine 35 [running]:
github.com/timtadh/fs2/errors.Errorf(0x6d6fa0, 0x4b, 0xc8202f2d70, 0x4, 0x4, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/errors/error.go:16 +0x89
github.com/timtadh/fs2/bptree.(*internal).updateK(0x7fd0be3a4000, 0x0, 0x2, 0x7fd0be3a1020, 0x4, 0xfe0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/internal.go:229 +0x5ff
github.com/timtadh/fs2/bptree.(*BpTree).internalDelete.func4.1(0x7fd0be3a1020, 0x4, 0xfe0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/remove.go:118 +0x63
github.com/timtadh/fs2/bptree.(*BpTree).firstKey.func2(0x7fd0be3a1000, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/first.go:20 +0xed
github.com/timtadh/fs2/bptree.(*BpTree).do.func1(0x7fd0be3a1000, 0x1000, 0x1000, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/do.go:103 +0xe7
github.com/timtadh/fs2/fmap.(*BlockFile).Do(0xc8200124c0, 0xc8000, 0x1, 0xc8202f2f80, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/fmap/fmap.go:563 +0xb6
github.com/timtadh/fs2/bptree.(*BpTree).do(0xc8200108a0, 0xc8000, 0xc8202f2fe0, 0xc8202f2fd0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/do.go:107 +0x69
github.com/timtadh/fs2/bptree.(*BpTree).firstKey(0xc8200108a0, 0xc8000, 0xc8202f3020, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/first.go:22 +0x6f
github.com/timtadh/fs2/bptree.(*BpTree).internalDelete.func4(0x7fd0be3a4000, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/remove.go:119 +0x93
github.com/timtadh/fs2/bptree.(*BpTree).do.func1(0x7fd0be3a4000, 0x1000, 0x1000, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/do.go:101 +0x98
github.com/timtadh/fs2/fmap.(*BlockFile).Do(0xc8200124c0, 0xcb000, 0x1, 0xc8202f3170, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/fmap/fmap.go:563 +0xb6
github.com/timtadh/fs2/bptree.(*BpTree).do(0xc8200108a0, 0xcb000, 0xc8202f3300, 0x6ec470, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/do.go:107 +0x69
github.com/timtadh/fs2/bptree.(*BpTree).doInternal(0xc8200108a0, 0xcb000, 0xc8202f3300, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/do.go:43 +0x4d
github.com/timtadh/fs2/bptree.(*BpTree).internalDelete(0xc8200108a0, 0x0, 0xcb000, 0x0, 0xc8203a2000, 0x4, 0x4, 0xc8202f3530, 0x7fd0c15d7970, 0x0, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/remove.go:120 +0x894
github.com/timtadh/fs2/bptree.(*BpTree).delete(0xc8200108a0, 0x0, 0xcb000, 0x0, 0xc8203a2000, 0x4, 0x4, 0xc8202f3530, 0xc8203a2000, 0x0, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/remove.go:58 +0x120
github.com/timtadh/fs2/bptree.(*BpTree).remove(0xc8200108a0, 0xcb000, 0xc8203a2000, 0x4, 0x4, 0xc8202f3530, 0x4, 0x4, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/remove.go:35 +0x83
github.com/timtadh/fs2/bptree.(*BpTree).Remove(0xc8200108a0, 0xc8203a2000, 0x4, 0x4, 0xc8202f3530, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/remove.go:25 +0x6d
github.com/timtadh/fs2/bptree.(*Varchar).szDel(0xc82001a720, 0x1000, 0xcc000, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:413 +0x2e3
github.com/timtadh/fs2/bptree.(*Varchar).indexRemove(0xc82001a720, 0x1000, 0xcc000, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:425 +0x5c
github.com/timtadh/fs2/bptree.(*Varchar).Alloc(0xc82001a720, 0x68, 0xcc000, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:220 +0x52e
github.com/timtadh/fs2/bptree.(*Varchar).allocNew(0xc82001a720, 0x68, 0x78, 0x0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:245 +0x12a
github.com/timtadh/fs2/bptree.(*Varchar).Alloc(0xc82001a720, 0x68, 0x0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:218 +0x4d7
github.com/timtadh/fs2/bptree.(*BpTree).checkValue(0xc8200108c0, 0xc82065b1f0, 0x68, 0x68, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:16 +0x9e
github.com/timtadh/fs2/bptree.(*BpTree).Add(0xc8200108c0, 0xc8200c6120, 0x5c, 0x5c, 0xc82065b1f0, 0x68, 0x68, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:51 +0x254
github.com/timtadh/sfp/types/graph.(*Node).cache(0xc820613a80, 0x7fd0bfde3438, 0xc8200109a0, 0x7fd0bfde33b0, 0xc8200108c0, 0xc8200c6120, 0x5c, 0x5c, 0xc8201b7240, 0x3, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/types/graph/node.go:304 +0x299
github.com/timtadh/sfp/types/graph.(*Node).Children(0xc820613a80, 0xc8201b7240, 0x3, 0x4, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/types/graph/node.go:286 +0xa55
github.com/timtadh/sfp/miners/absorbing.walk(0xc820012580, 0x0, 0x0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/absorbing/mine.go:176 +0x166
github.com/timtadh/sfp/miners/absorbing.RejectingWalk.func1(0xc820012580, 0xc820258120, 0xc8202580c0, 0xc820258060)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/absorbing/mine.go:149 +0x30
created by github.com/timtadh/sfp/miners/absorbing.RejectingWalk
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/absorbing/mine.go:163 +0xbb

goroutine 1 [runnable]:
github.com/timtadh/sfp/stores/bytes_subgraph.(*BpTree).kvIter.func1(0xc8203fc4c0, 0xc, 0xc, 0xc8206d9400, 0x0, 0x0, 0xc820368480)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/stores/bytes_subgraph/wrapper.go:254
github.com/timtadh/sfp/stores/bytes_subgraph.Do(0xc8202f6dd8, 0xc8203fc060, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/stores/bytes_subgraph/wrapper.go:88 +0x129
github.com/timtadh/sfp/stores/bytes_subgraph.(*BpTree).DoFind(0xc8201320c0, 0xc8203fc050, 0xc, 0xc, 0xc8203fc060, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/stores/bytes_subgraph/wrapper.go:339 +0x68
github.com/timtadh/sfp/types/graph.edgeChain(0xc820096000, 0xc8206be300, 0x5c, 0xc8206f1ef0, 0x5, 0x5, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/types/graph/node.go:212 +0x359
github.com/timtadh/sfp/types/graph.(*Node).FindNode(0xc82056d680, 0xc820096000, 0xc8206be300, 0x0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/types/graph/node.go:159 +0x3b3
github.com/timtadh/sfp/types/graph.(*Node).Parents(0xc82056d680, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/types/graph/node.go:128 +0x50d
github.com/timtadh/sfp/lattice.lattice(0x7fd0be09b838, 0xc82056d680, 0x7fd0bfdf5738, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/lattice/lattice.go:35 +0x359
github.com/timtadh/sfp/lattice.MakeLattice(0x7fd0be09b838, 0xc82056d680, 0xb00, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/lattice/lattice.go:16 +0xaf
github.com/timtadh/sfp/miners/absorbing.(*Walker).PrMatrices(0xc820012580, 0x7fd0be09b838, 0xc82056d680, 0xc820464440, 0xc8204c8c00, 0xa54, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/absorbing/mine.go:37 +0x54
github.com/timtadh/sfp/miners/absorbing.(*MatrixReporter).Report(0xc820225980, 0x7fd0be09b838, 0xc82056d680, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/absorbing/reporter.go:43 +0x62
github.com/timtadh/sfp/miners/reporters.(*Chain).Report(0xc820164800, 0x7fd0be09b838, 0xc82056d680, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/reporters/chain.go:18 +0xcb
github.com/timtadh/sfp/miners/walker.(*Walker).Mine(0xc820012580, 0x7fd0be09bc68, 0xc820096000, 0x7fd0be09bd80, 0xc820164800, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/walker/walker.go:58 +0x219
github.com/timtadh/sfp/miners/absorbing.(*Walker).Mine(0xc820012580, 0x7fd0be09bc68, 0xc820096000, 0x7fd0be09bd80, 0xc820164740, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/absorbing/mine.go:140 +0x1bf
main.main()
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/main.go:556 +0x1737

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/hendersont/srcs/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 36 [chan receive]:
github.com/timtadh/sfp/miners/walker.(*Walker).RejectingWalk.func1(0xc820258060, 0xc820012580, 0xc820258180, 0xc8202580c0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/walker/walker.go:75 +0x5d
created by github.com/timtadh/sfp/miners/walker.(*Walker).RejectingWalk
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/walker/walker.go:89 +0x71

There was error during the mining process
Unknown block type
goroutine 1 [running]:
github.com/timtadh/fs2/errors.Errorf(0x6a9b00, 0x12, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/errors/error.go:16 +0x89
github.com/timtadh/fs2/bptree.(*BpTree).insert(0xc8200108a0, 0xc8000, 0xc82044b980, 0x4, 0x4, 0xc82044b990, 0x8, 0x8, 0x1, 0xc8202f6070, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:110 +0x226
github.com/timtadh/fs2/bptree.(*BpTree).internalInsert(0xc8200108a0, 0xcb000, 0xc82044b980, 0x4, 0x4, 0xc82044b990, 0x8, 0x8, 0x1, 0x0, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:141 +0x172
github.com/timtadh/fs2/bptree.(*BpTree).insert(0xc8200108a0, 0xcb000, 0xc82044b980, 0x4, 0x4, 0xc82044b990, 0x8, 0x8, 0xc82044b901, 0x0, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:106 +0x144
github.com/timtadh/fs2/bptree.(*BpTree).add(0xc8200108a0, 0xcb000, 0xc82044b980, 0x4, 0x4, 0xc82044b990, 0x8, 0x8, 0x1, 0xc82044b990, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:65 +0xab
github.com/timtadh/fs2/bptree.(*BpTree).Add(0xc8200108a0, 0xc82044b980, 0x4, 0x4, 0xc82044b990, 0x8, 0x8, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:55 +0x2fb
github.com/timtadh/fs2/bptree.(*Varchar).szAdd(0xc82001a720, 0x1000, 0xc8000, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:401 +0x2bf
github.com/timtadh/fs2/bptree.(*Varchar).indexAdd(0xc82001a720, 0x1000, 0xc8000, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:417 +0x5c
github.com/timtadh/fs2/bptree.(*Varchar).free(0xc82001a720, 0xc8000, 0x1000, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:395 +0x734
github.com/timtadh/fs2/bptree.(*Varchar).allocNew(0xc82001a720, 0x2c, 0x3c, 0x0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:241 +0xea
github.com/timtadh/fs2/bptree.(*Varchar).Alloc(0xc82001a720, 0x2c, 0x0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:218 +0x4d7
github.com/timtadh/fs2/bptree.(*BpTree).newVarcharKey(0xc8200108c0, 0xce000, 0xc8205c27b0, 0x2c, 0x2c, 0x7fd0be3a7001, 0x0, 0x0, 0x0, 0x0, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:210 +0x19e
github.com/timtadh/fs2/bptree.(*BpTree).leafInsert(0xc8200108c0, 0xce000, 0xc8205c27b0, 0x2c, 0x2c, 0xc82044b850, 0x8, 0x8, 0x6ec401, 0x5226dd, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:227 +0xb9
github.com/timtadh/fs2/bptree.(*BpTree).insert(0xc8200108c0, 0xce000, 0xc8205c27b0, 0x2c, 0x2c, 0xc82044b850, 0x8, 0x8, 0x545a01, 0x7fd0be3a3fa4, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:108 +0x1c0
github.com/timtadh/fs2/bptree.(*BpTree).internalInsert(0xc8200108c0, 0xf6000, 0xc8205c27b0, 0x2c, 0x2c, 0xc82044b850, 0x8, 0x8, 0x1, 0x0, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:141 +0x172
github.com/timtadh/fs2/bptree.(*BpTree).insert(0xc8200108c0, 0xf6000, 0xc8205c27b0, 0x2c, 0x2c, 0xc82044b850, 0x8, 0x8, 0x1, 0x3c, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:106 +0x144
github.com/timtadh/fs2/bptree.(*BpTree).add(0xc8200108c0, 0xf6000, 0xc8205c27b0, 0x2c, 0x2c, 0xc82044b850, 0x8, 0x8, 0x1, 0x0, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:65 +0xab
github.com/timtadh/fs2/bptree.(*BpTree).Add(0xc8200108c0, 0xc8205c27b0, 0x2c, 0x2c, 0xc82044b850, 0x8, 0x8, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:55 +0x2fb
github.com/timtadh/sfp/types/graph.(*Node).cache(0xc8203a81c0, 0x7fd0bfde3438, 0xc8200109a0, 0x7fd0bfde33b0, 0xc8200108c0, 0xc8205c27b0, 0x2c, 0x2c, 0xc8201e3540, 0x2, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/types/graph/node.go:304 +0x299
github.com/timtadh/sfp/types/graph.(*Node).Children(0xc8203a81c0, 0xc8201e3540, 0x2, 0x2, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/types/graph/node.go:286 +0xa55
github.com/timtadh/sfp/lattice.lattice(0x7fd0be09b838, 0xc82056d680, 0x7fd0bfdf5738, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/lattice/lattice.go:55 +0x9fd
github.com/timtadh/sfp/lattice.MakeLattice(0x7fd0be09b838, 0xc82056d680, 0xb00, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/lattice/lattice.go:16 +0xaf
github.com/timtadh/sfp/miners/absorbing.(*Walker).PrMatrices(0xc820012580, 0x7fd0be09b838, 0xc82056d680, 0xc820464440, 0xc8204c8c00, 0xa54, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/absorbing/mine.go:37 +0x54
github.com/timtadh/sfp/miners/absorbing.(*MatrixReporter).Report(0xc820225980, 0x7fd0be09b838, 0xc82056d680, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/absorbing/reporter.go:43 +0x62
github.com/timtadh/sfp/miners/reporters.(*Chain).Report(0xc820164800, 0x7fd0be09b838, 0xc82056d680, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/reporters/chain.go:18 +0xcb
github.com/timtadh/sfp/miners/walker.(*Walker).Mine(0xc820012580, 0x7fd0be09bc68, 0xc820096000, 0x7fd0be09bd80, 0xc820164800, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/walker/walker.go:58 +0x219
github.com/timtadh/sfp/miners/absorbing.(*Walker).Mine(0xc820012580, 0x7fd0be09bc68, 0xc820096000, 0x7fd0be09bd80, 0xc820164740, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/absorbing/mine.go:140 +0x1bf
main.main()
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/main.go:556 +0x1737

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/hendersont/srcs/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 35 [chan send]:
github.com/timtadh/sfp/miners/absorbing.RejectingWalk.func1(0xc820012580, 0xc820258120, 0xc8202580c0, 0xc820258060)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/absorbing/mine.go:151 +0x8f
created by github.com/timtadh/sfp/miners/absorbing.RejectingWalk
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/absorbing/mine.go:163 +0xbb

goroutine 36 [chan receive]:
github.com/timtadh/sfp/miners/walker.(*Walker).RejectingWalk.func1(0xc820258060, 0xc820012580, 0xc820258180, 0xc8202580c0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/walker/walker.go:75 +0x5d
created by github.com/timtadh/sfp/miners/walker.(*Walker).RejectingWalk
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/miners/walker/walker.go:89 +0x71

Command exited with non-zero status 1
```

**Comment by timtadh** [comment]
likely a concurrency bug from the consumer.
