### ISSUE TITLE
Double Internal put

### ISSUE THREAD

**Issue by timtadh** [timtadh/fs2#4]
Not sure if this is a real issue or a usage error

```
2015/12/03 20:56:41 <internal (debug) (vchar <nil>) meta: <{1 4 39 340}>, keys: <[[0 0 0 24] [0 0 0 28] [0 0 0 32] [0 0 0 36] [0 0 0 40] [0 0 0 44] [0 0 0 48] [0 0 0 52] [0 0 0 56] [0 0 0 60] [0 0 0 64] [0 0 0 68] [0 0 0 72] [0 0 0 76] [0 0 0 80] [0 0 0 84] [0 0 0 88] [0 0 0 92] [0 0 0 96] [0 0 0 100] [0 0 0 104] [0 0 0 108] [0 0 0 112] [0 0 0 116] [0 0 0 120] [0 0 0 124] [0 0 0 128] [0 0 0 132] [0 0 0 136] [0 0 0 140] [0 0 0 144] [0 0 0 148] [0 0 0 152] [0 0 0 156] [0 0 0 164] [0 0 0 168] [0 0 0 176] [0 0 0 180] [0 0 0 208]]>, ptrs: <[1024000 765952 4583424 4440064 65822720 49954816 19202048 56877056 49369088 91881472 13000704 27590656 50708480 8515584 26238976 20332544 36560896 32595968 14405632 29827072 27242496 111857664 65892352 107053056 41676800 91000832 57516032 108855296 43786240 99532800 108916736 214274048 215560192 165625856 338407424 209829888 349868032 349970432 349982720]>>
2015/12/03 20:56:41 key [0 0 0 168] v was nil
2015/12/03 20:56:41 replacing [0 0 0 164]
2015/12/03 20:56:41 <internal (debug) (vchar <nil>) meta: <{1 4 39 340}>, keys: <[[0 0 0 24] [0 0 0 28] [0 0 0 32] [0 0 0 36] [0 0 0 40] [0 0 0 44] [0 0 0 48] [0 0 0 52] [0 0 0 56] [0 0 0 60] [0 0 0 64] [0 0 0 68] [0 0 0 72] [0 0 0 76] [0 0 0 80] [0 0 0 84] [0 0 0 88] [0 0 0 92] [0 0 0 96] [0 0 0 100] [0 0 0 104] [0 0 0 108] [0 0 0 112] [0 0 0 116] [0 0 0 120] [0 0 0 124] [0 0 0 128] [0 0 0 132] [0 0 0 136] [0 0 0 140] [0 0 0 144] [0 0 0 148] [0 0 0 152] [0 0 0 156] [0 0 0 164] [0 0 0 168] [0 0 0 176] [0 0 0 180] [0 0 0 208]]>, ptrs: <[1024000 765952 4583424 4440064 65822720 49954816 19202048 56877056 49369088 91881472 13000704 27590656 50708480 8515584 26238976 20332544 36560896 32595968 14405632 29827072 27242496 111857664 65892352 107053056 41676800 91000832 57516032 108855296 43786240 99532800 108916736 214274048 215560192 165625856 338407424 209829888 349868032 349970432 349982720]>>
2015/12/03 20:56:41 was removing: [0 0 0 164]
2015/12/03 20:56:41 n: 921600, parent: 0, sibling: 209829888, okid 338407424, kid: 338407424
2015/12/03 20:56:41 internal already had key [0 0 0 168], at 35, was going to put it at 34, replacing [0 0 0 164]
goroutine 34 [running]:
github.com/timtadh/fs2/errors.Errorf(0x6e3f00, 0x4b, 0xc829ce47b0, 0x4, 0x4, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/errors/error.go:16 +0x89
github.com/timtadh/fs2/bptree.(*internal).updateK(0x7f66a01dd000, 0x0, 0x22, 0x7f66b43b7020, 0x4, 0xfe0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/internal.go:229 +0x5ff
github.com/timtadh/fs2/bptree.(*BpTree).internalDelete.func4.1(0x7f66b43b7020, 0x4, 0xfe0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/remove.go:118 +0x63
github.com/timtadh/fs2/bptree.(*BpTree).firstKey.func2(0x7f66b43b7000, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/first.go:20 +0xed
github.com/timtadh/fs2/bptree.(*BpTree).do.func1(0x7f66b43b7000, 0x1000, 0x1000, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/do.go:103 +0xe7
github.com/timtadh/fs2/fmap.(*BlockFile).Do(0xc8251ab440, 0x142bb000, 0x1, 0xc829ce49c0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/fmap/fmap.go:563 +0xb6
github.com/timtadh/fs2/bptree.(*BpTree).do(0xc82636ff80, 0x142bb000, 0xc829ce4a20, 0xc829ce4a10, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/do.go:107 +0x69
github.com/timtadh/fs2/bptree.(*BpTree).firstKey(0xc82636ff80, 0x142bb000, 0xc829ce4a60, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/first.go:22 +0x6f
github.com/timtadh/fs2/bptree.(*BpTree).internalDelete.func4(0x7f66a01dd000, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/remove.go:119 +0x93
github.com/timtadh/fs2/bptree.(*BpTree).do.func1(0x7f66a01dd000, 0x1000, 0x1000, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/do.go:101 +0x98
github.com/timtadh/fs2/fmap.(*BlockFile).Do(0xc8251ab440, 0xe1000, 0x1, 0xc829ce4bb0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/fmap/fmap.go:563 +0xb6
github.com/timtadh/fs2/bptree.(*BpTree).do(0xc82636ff80, 0xe1000, 0xc829ce4d40, 0x6f9da0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/do.go:107 +0x69
github.com/timtadh/fs2/bptree.(*BpTree).doInternal(0xc82636ff80, 0xe1000, 0xc829ce4d40, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/do.go:43 +0x4d
github.com/timtadh/fs2/bptree.(*BpTree).internalDelete(0xc82636ff80, 0x0, 0xe1000, 0xc81c000, 0xc823239630, 0x4, 0x4, 0xc829ce4f70, 0x142bb000, 0x0, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/remove.go:120 +0x894
github.com/timtadh/fs2/bptree.(*BpTree).delete(0xc82636ff80, 0x0, 0xe1000, 0x0, 0xc823239630, 0x4, 0x4, 0xc829ce4f70, 0xc823239630, 0x0, ...)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/remove.go:58 +0x120
github.com/timtadh/fs2/bptree.(*BpTree).remove(0xc82636ff80, 0xe1000, 0xc823239630, 0x4, 0x4, 0xc829ce4f70, 0x4, 0x4, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/remove.go:35 +0x83
github.com/timtadh/fs2/bptree.(*BpTree).Remove(0xc82636ff80, 0xc823239630, 0x4, 0x4, 0xc829ce4f70, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/remove.go:25 +0x6d
github.com/timtadh/fs2/bptree.(*Varchar).szDel(0xc8224c2780, 0xa4, 0x14c4ef5c, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:413 +0x2e3
github.com/timtadh/fs2/bptree.(*Varchar).indexRemove(0xc8224c2780, 0xa4, 0x14c4ef5c, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:425 +0x5c
github.com/timtadh/fs2/bptree.(*Varchar).Alloc(0xc8224c2780, 0x8c, 0x14c4ef5c, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:220 +0x52e
github.com/timtadh/fs2/bptree.(*BpTree).checkValue(0xc82636ffc0, 0xc8294ad950, 0x8c, 0x8c, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:16 +0x9e
github.com/timtadh/fs2/bptree.(*BpTree).Add(0xc82636ffc0, 0xc8294a4cf0, 0x88, 0x88, 0xc8294ad950, 0x8c, 0x8c, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/fs2/bptree/insert.go:51 +0x254
github.com/timtadh/sfp/stores/bytes_subgraph.(*BpTree).Add(0xc8251ab4c0, 0xc8294a4cf0, 0x88, 0x88, 0xc82ee45200, 0x0, 0x0)
        /home/hendersont/stuff/research/sfp/src/github.com/timtadh/sfp/stores/bytes_subgraph/wrapper.go:237 +0x16a
```

**Comment by timtadh** [comment]
Another trace:

```
2016/03/15 22:00:46 <internal (debug) (vchar <nil>) meta: <{1 4 18 340}>, keys: <[[0 0 0 24] [0 0 0 28] [0 0 0 32] [0 0 0 36] [0 0 0 40] [0 0 0 44] [0 0 0 48] [0 0 0 52] [0
 0 0 56] [0 0 0 64] [0 0 0 68] [0 0 0 72] [0 0 0 76] [0 0 0 96] [0 0 0 100] [0 0 0 144] [0 0 0 148] [0 0 5 96]]>, ptrs: <[1024000 765952 4620288 4550656 4448256 4567040 689
7664 6594560 141611008 4222976 4243456 4263936 4276224 98893824 99127296 217366528 713854976 241217536]>>
2016/03/15 22:00:46 key [0 0 0 144] v was nil
2016/03/15 22:00:46 replacing [0 0 5 96]
2016/03/15 22:00:46 <internal (debug) (vchar <nil>) meta: <{1 4 18 340}>, keys: <[[0 0 0 24] [0 0 0 28] [0 0 0 32] [0 0 0 36] [0 0 0 40] [0 0 0 44] [0 0 0 48] [0 0 0 52] [0
 0 0 56] [0 0 0 64] [0 0 0 68] [0 0 0 72] [0 0 0 76] [0 0 0 96] [0 0 0 100] [0 0 0 144] [0 0 0 148] [0 0 5 96]]>, ptrs: <[1024000 765952 4620288 4550656 4448256 4567040 689
7664 6594560 141611008 4222976 4243456 4263936 4276224 98893824 99127296 217366528 713854976 241217536]>>
2016/03/15 22:00:46 was removing: [0 0 5 96]
2016/03/15 22:00:46 n: 921600, parent: 0, sibling: 0, okid 736165888, kid: 241217536
2016/03/15 22:00:46 internal already had key [0 0 0 144], at 15, was going to put it at 17, replacing [0 0 5 96]
goroutine 1 [running]:
github.com/timtadh/fs2/errors.Errorf(0x6ddc20, 0x4b, 0xc84662a0e8, 0x4, 0x4, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/errors/error.go:16 +0x89
github.com/timtadh/fs2/bptree.(*internal).updateK(0x7fb54f1dc000, 0x0, 0x11, 0x7fb55d706020, 0x4, 0xfe0, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/internal.go:229 +0x5ff
github.com/timtadh/fs2/bptree.(*BpTree).internalDelete.func4.1(0x7fb55d706020, 0x4, 0xfe0, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/remove.go:118 +0x63
github.com/timtadh/fs2/bptree.(*BpTree).firstKey.func2(0x7fb55d706000, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/first.go:20 +0xed
github.com/timtadh/fs2/bptree.(*BpTree).do.func1(0x7fb55d706000, 0x1000, 0x1000, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/do.go:103 +0xe7
github.com/timtadh/fs2/fmap.(*BlockFile).Do(0xc8250f15c0, 0xe60b000, 0x1, 0xc84662a2f8, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/fmap/fmap.go:563 +0xb6
github.com/timtadh/fs2/bptree.(*BpTree).do(0xc8245d51a0, 0xe60b000, 0xc84662a358, 0xc84662a348, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/do.go:107 +0x69
github.com/timtadh/fs2/bptree.(*BpTree).firstKey(0xc8245d51a0, 0xe60b000, 0xc84662a398, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/first.go:22 +0x6f
github.com/timtadh/fs2/bptree.(*BpTree).internalDelete.func4(0x7fb54f1dc000, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/remove.go:119 +0x93
github.com/timtadh/fs2/bptree.(*BpTree).do.func1(0x7fb54f1dc000, 0x1000, 0x1000, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/do.go:101 +0x98
github.com/timtadh/fs2/fmap.(*BlockFile).Do(0xc8250f15c0, 0xe1000, 0x1, 0xc84662a4e8, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/fmap/fmap.go:563 +0xb6
github.com/timtadh/fs2/bptree.(*BpTree).do(0xc8245d51a0, 0xe1000, 0xc84662a678, 0x6f03c8, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/do.go:107 +0x69
github.com/timtadh/fs2/bptree.(*BpTree).doInternal(0xc8245d51a0, 0xe1000, 0xc84662a678, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/do.go:43 +0x4d
github.com/timtadh/fs2/bptree.(*BpTree).internalDelete(0xc8245d51a0, 0x0, 0xe1000, 0x0, 0xc83d5e567c, 0x4, 0x4, 0xc84662a8a8, 0x2be10000, 0x0, ...)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/remove.go:120 +0x895
github.com/timtadh/fs2/bptree.(*BpTree).delete(0xc8245d51a0, 0x0, 0xe1000, 0x0, 0xc83d5e567c, 0x4, 0x4, 0xc84662a8a8, 0xc83d5e567c, 0x0, ...)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/remove.go:58 +0x120
github.com/timtadh/fs2/bptree.(*BpTree).remove(0xc8245d51a0, 0xe1000, 0xc83d5e567c, 0x4, 0x4, 0xc84662a8a8, 0x4, 0x4, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/remove.go:35 +0x83
github.com/timtadh/fs2/bptree.(*BpTree).Remove(0xc8245d51a0, 0xc83d5e567c, 0x4, 0x4, 0xc84662a8a8, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/remove.go:25 +0x6d
github.com/timtadh/fs2/bptree.(*Varchar).szDel(0xc82271a4e0, 0x560, 0x2be12aa0, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:413 +0x2e3
github.com/timtadh/fs2/bptree.(*Varchar).indexRemove(0xc82271a4e0, 0x560, 0x2be12aa0, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:425 +0x5c
github.com/timtadh/fs2/bptree.(*Varchar).Alloc(0xc82271a4e0, 0x90, 0x2be12aa0, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/varchar.go:220 +0x52e
github.com/timtadh/fs2/bptree.(*BpTree).checkValue(0xc8245d52c0, 0xc825500d80, 0x90, 0x90, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/insert.go:16 +0x9e
github.com/timtadh/fs2/bptree.(*BpTree).Add(0xc8245d52c0, 0xc825500cf0, 0x8c, 0x8c, 0xc825500d80, 0x90, 0x90, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/fs2/bptree/insert.go:51 +0x254
github.com/timtadh/sfp/stores/bytes_subgraph.(*BpTree).Add(0xc8250f1800, 0xc825500cf0, 0x8c, 0x8c, 0xc83c60a080, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/stores/bytes_subgraph/wrapper.go:238 +0x16a
github.com/timtadh/sfp/types/digraph.(*EmbListNode).Save(0xc82d900a20, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/types/digraph/emblist_node.go:61 +0x1e7
github.com/timtadh/sfp/types/digraph.cache(0xc8200cc000, 0x7fb613a8c448, 0xc820010ac0, 0x7fb613a8c3b0, 0xc8200109a0, 0xc82c71a400, 0x7c, 0x7c, 0xc82b02ea00, 0xa, ...)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/types/digraph/cached.go:33 +0x249
github.com/timtadh/sfp/types/digraph.children(0x7fb60860f3e8, 0xc82593d0b0, 0xc82001c000, 0x7fb613a8c3b0, 0xc8200109a0, 0x7fb613a8c448, 0xc820010ac0, 0xc82b02ea00, 0xa, 0x10, ...)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/types/digraph/children.go:118 +0xa7c
github.com/timtadh/sfp/types/digraph.(*EmbListNode).Children(0xc82593d0b0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/types/digraph/emblist_node.go:82 +0xd4
github.com/timtadh/sfp/types/digraph.(*EmbListNode).Children-fm(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/types/digraph/emblist_node.go:119 +0x41
github.com/timtadh/sfp/types/digraph.count(0x7fb60860f3e8, 0xc82593d0b0, 0xc84662b3b0, 0x7fb613a8c448, 0xc820010ac0, 0x676760, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/types/digraph/count.go:19 +0xd9
github.com/timtadh/sfp/types/digraph.(*EmbListNode).ChildCount(0xc82593d0b0, 0x0, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/types/digraph/emblist_node.go:119 +0x9e
github.com/timtadh/sfp/types/digraph.(*EmbListNode).Maximal(0xc82593d0b0, 0xc82593d0b0, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/types/digraph/emblist_node.go:123 +0x2d
github.com/timtadh/sfp/miners/reporters.(*Max).Report(0xc826669870, 0x7fb60860f380, 0xc82593d0b0, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/miners/reporters/max.go:26 +0x37
github.com/timtadh/sfp/miners/reporters.(*Chain).Report(0xc82621b220, 0x7fb60860f380, 0xc82593d0b0, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/miners/reporters/chain.go:16 +0xcb
github.com/timtadh/sfp/afp/miners/vsigram.(*Miner).mine(0xc82001a8a0, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/afp/miners/vsigram/mine.go:80 +0x247
github.com/timtadh/sfp/afp/miners/vsigram.(*Miner).Mine(0xc82001a8a0, 0x7fb60860f0d0, 0xc8200cc000, 0x7fb60860f210, 0xc82621b220, 0x7fb60860f128, 0xc82621a020, 0x0, 0x0)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/afp/miners/vsigram/mine.go:62 +0xdb
github.com/timtadh/sfp/cmd.Main(0xc82000a5e0, 0x0, 0x2, 0xc8200940f0, 0xc82001a330)
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/cmd/cmd.go:774 +0xd2c
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/cmd/cmd.go:774 +0xd2c
main.main()
        /home/hendersont/stuff/research/eecs-cc-deploy/code/sfp/sfp/src/github.com/timtadh/sfp/afp/main.go:351 +0xc00
```
